---
title: "Stuff"
author: "Franco C"
date: "2025-02-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
hist=read_excel("C:\\Users\\franc\\OneDrive\\Hawks25\\NECBLHISTORY_combined.xlsx")
```



```{r}
# Load necessary libraries
library(dplyr)
library(caret)


hist <- hist %>%
  filter(!is.na(AutoPitchType), 
         AutoPitchType != "Other", 
         PitchCall != "Undefined", 
         PitchCall != "BallIntentional", 
         PitcherThrows != "Both", 
         BatterSide != "Undefined",
         !is.na(SpinRate))


hist <- hist %>%
  mutate(
    PitchCall = case_when(
      PitchCall %in% c("StikeCalled", "Strikecalled") ~ "StrikeCalled",
      PitchCall == "BallinDirt" ~ "BallCalled",
      PitchCall %in% c("FoulBall", "FoulBallNotFieldable", "FoulBallFieldable") ~ "Foul",
      TRUE ~ PitchCall
    ),
    BatterSide = ifelse(BatterSide == "RIght", "Right", BatterSide),
    PitcherThrows = ifelse(PitcherThrows == "RIght", "Right", PitcherThrows)
  ) %>%
  mutate(
    Balls = factor(Balls, levels = c(0,1,2,3), ordered = TRUE),
    Strikes = factor(Strikes, levels = c(0,1,2), ordered = TRUE),
    PitchCall = factor(PitchCall),
    PitcherThrows = factor(PitcherThrows, levels = c("Left", "Right")),
    BatterSide = factor(BatterSide, levels = c("Left", "Right"))
  )

```


```{r}
library(caret)
set.seed(2425)  


train_index <- createDataPartition(hist$PitchCall, p = 0.7, list = FALSE)
train <- hist[train_index, ]
vali <- hist[-train_index, ]

```

```{r}
set.seed(2425)
library(randomForest)

rf_model <- randomForest(
  PitchCall ~ PitcherThrows+BatterSide+Balls+Strikes+RelSpeed+SpinRate+InducedVertBreak+HorzBreak+PlateLocHeight+PlateLocSide,
  data = train,  
  ntree = 100,  
  mtry = sqrt(10),
  importance = TRUE,
)

print(rf_model)
```
```{r}
varImpPlot(rf_model, main = "Feature Importance in Random Forest")

rf_pred <- predict(rf_model, newdata = vali)

# Compute Confusion Matrix
conf_matrix <- confusionMatrix(rf_pred, vali$PitchCall)
print(conf_matrix)


```
```{r}
rf_prob <- predict(rf_model, newdata = vali, type = "prob")

y_actual <- model.matrix(~ PitchCall - 1, data = vali)

brier_score <- mean(rowSums((rf_prob - y_actual)^2) / ncol(y_actual))
cat("Brier Score:", brier_score, "\n")


log_loss <- function(y_true, y_pred) {
  eps <- 1e-15  
  y_pred <- pmax(pmin(y_pred, 1 - eps), eps)  
  -mean(rowSums(y_true * log(y_pred)))
}

y_true <- model.matrix(~ PitchCall - 1, data = vali)

log_loss_score <- log_loss(y_true, rf_prob)
cat("Log Loss:", log_loss_score, "\n")

num_classes <- length(unique(vali$PitchCall))
baseline_probs <- matrix(1 / num_classes, nrow = nrow(y_true), ncol = num_classes)

baseline_log_loss <- -mean(rowSums(y_true * log(baseline_probs + 1e-15)))
cat("Baseline Log Loss:", baseline_log_loss, "\n")
improvement <- ((1.8 - 1.14) / 1.8) * 100
cat("Log Loss Improvement:", improvement, "%\n")
```


```{r}
preds <- as.data.frame(rf_prob)

preds$Actual <- vali$PitchCall
preds$Predicted <- predict(rf_model, newdata = vali)
preds$Strike=preds$StrikeCalled+preds$StrikeSwinging
preds <- cbind(preds, vali[, c("PitcherThrows", "BatterSide", "Balls", "Strikes", "AutoPitchType", "RelSpeed", "SpinRate", "InducedVertBreak", "HorzBreak", "PlateLocHeight", "PlateLocSide")])

View(preds)
```



```{r}
test_fastball <- data.frame(
  PitcherThrows = factor("Right", levels = levels(train$PitcherThrows)),
  BatterSide = factor("Left", levels = levels(train$BatterSide)),
  Balls = factor(3, levels = levels(train$Balls), ordered = TRUE),
  Strikes = factor(2, levels = levels(train$Strikes), ordered = TRUE),
  RelSpeed = 90,  
  SpinRate = 2276,  
  InducedVertBreak = 21.6,  
  HorzBreak = 8.74,  
  PlateLocHeight = 1.96,  
  PlateLocSide = -0.6  
)

single_prediction <- predict(rf_model, newdata = test_fastball, type = "prob")

print(single_prediction)


```
```{r}

```

```{r}
# Ensure we bring Pitcher from vali (which comes from hist)
preds <- preds %>%
  mutate(Pitcher = vali$Pitcher)

```

```{r}
preds <- preds %>%
  mutate(ActualGainStrike = ifelse(Strikes %in% c(0,1) & Actual %in% c("StrikeCalled", "Foul", "StrikeSwinging"), 1,
                            ifelse(Strikes == 2 & Actual %in% c("StrikeCalled", "StrikeSwinging"), 1, 0)))



```

```{r}
preds <- preds %>%
  mutate(
    GainStrike = ifelse(Strikes %in% c(0, 1), Foul + StrikeCalled + StrikeSwinging, StrikeCalled + StrikeSwinging),
    ActualGainStrike = ifelse(Strikes %in% c(0, 1) & Actual %in% c("StrikeCalled", "Foul", "StrikeSwinging"), 1,
                       ifelse(Strikes == 2 & Actual %in% c("StrikeCalled", "StrikeSwinging"), 1, 0))
  )

```




